### ISSUE TITLE
Unable to import One2many relations

### ISSUE THREAD

**Issue by ghost** [gmarczynski/odoo-web-progress#14]
Odoo v14
For instance, export a BoM file with the following details (multiple BoM records):
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>

<body>

product_tmpl_id | code | sequence | type | bom_line_ids/product_id | bom_line_ids/product_uom_id | bom_line_ids/product_qty
-- | -- | -- | -- | -- | -- | --

</body>

</html>

Please try to import it then. Odoo will give traceback saying a mandatory field "BoM type" not set.

**Comment by gmarczynski** [comment]
I think that this kind of error cannot be related to this module. 

Are you sure that without `web_progress` installed the import is successful and only after installation of this module the import fails?

**Comment by ghost** [comment]
> Are you sure that without `web_progress` installed the import is successful and only after installation of this module the import fails?

Yes.

**Comment by gmarczynski** [comment]
I believe that I found the bug and fixed it.
