### ISSUE TITLE
QUnit test failed

### ISSUE THREAD

**Issue by niulinlnc** [gmarczynski/odoo-web-progress#2]
Date | Level | Type | Message
-- | -- | -- | --
06/24/2019 01:10:11 | ERROR | server | "QUnit test failed: "fields > basic_fields > FieldProgressBar > Field ProgressBar: max_value should update" [message: "The initial value of the progress bar should be correct", actual: "", expected: "10 / 2"]
06/24/2019 01:10:11 | ERROR | server | "QUnit test failed: "fields > basic_fields > FieldProgressBar > Field ProgressBar: max_value should update" [message: "The value of the progress bar should be correct after the update", actual: "", expected: "999 / 5"]

**Comment by gmarczynski** [comment]
Thanks! Fixed in v1.2
