### ISSUE TITLE
16.0: Export warning

### ISSUE THREAD

**Issue by pafnow** [gmarczynski/odoo-web-progress#29]
Last one for today ;)

Another warning upon using the export feature, doesn't seems to have any impact on the feature though

```
2023-02-03 20:29:41,151 10965 WARNING test-prod230202 odoo.http: <function odoo.addons.web.controllers.export.index> called ignoring args {'token'}
```

**Comment by gmarczynski** [comment]
Thank you. I looks though that this warning is not related to `web_progress`. I tested with and without my module and the warning was always there. 
It's actual reason may be here: odoo/addons/web/static/src/core/network/download.js:473
```
data.append("token", "dummy-because-api-expects-one");
```

I close this issue.
