### ISSUE TITLE
Odoo 15.0 Export pivot to Excel 

### ISSUE THREAD

**Issue by emadco88** [gmarczynski/odoo-web-progress#37]
There is a syntax error while exporting pivot to Excel due to this code:
        const context = JSON.parse(options.data.context)

as options.data.context is undefined.

I solve this error via:
        const context = options.data.context ? JSON.parse(options.data.context) : {};

I am not an JS expert, so I do not know are there side effects for this modification?

**Comment by gmarczynski** [comment]
Hi, thank you for the bug report. Your solution is OK, no side effects. I already pushed a bit different fix as well.
Cheers!
