### ISSUE TITLE
Can't get progress to work on Odoo 15

### ISSUE THREAD

**Issue by metalmonkey69** [gmarczynski/odoo-web-progress#38]
I have created this test function in a custom TransientModel which is called by a "Process" button to process a file.

    def process_file(self):

        web_progress_obj = self.env['web.progress']
        res = web_progress_obj.get_all_progress()

        progress_code = str(uuid.uuid4())
        partner_obj = self.env['res.partner'].with_context(progress_code=progress_code)
        data = partner_obj.search([])
        print("%s %s" % (len(data), data))
        for rec in data:
            data.web_progress_percent(0, "Start")
            print(rec.name)
            sleep(10)
            partner_obj.web_progress_percent(50, "Middle")
            print(rec.name)
            sleep(10)
            partner_obj.web_progress_percent(100, "End")
            print(rec.name)
            sleep(10)

        return

The browser side only shows the standard odoo "loading..."

I tried to put this line as shown in the readme.rst

`for rec in data.with_progress(msg="Message"):`

but odoo reports the error ... Invalid property 'with_progress'

What did I miss ?

**Comment by gmarczynski** [comment]
Hi,

The progress code is already injected into the `self._context` by the web client. Try this:

```python
def process_file(self):
    partner_obj = self.env['res.partner']
    data = partner_obj.search([])
    print("%s %s" % (len(data), data))
    for rec in data.with_progress(msg="Message"):
        print(rec.name)
        sleep(0.1)
    return
``` 
Of course also make sure that `web_progress` module is installed in your database ;)

**Comment by peterhoth** [comment]
No progress pop-up but i notice that there is an icon on the top right 

![image](https://github.com/gmarczynski/odoo-web-progress/assets/7699250/2688a2a4-b521-420b-8a1a-2f4640c9c997)

**Comment by metalmonkey69** [comment]
I changed my code to
```python
    def process_file(self):
        partner_obj = self.env['res.partner']
        data = partner_obj.search([])
        print("%s %s" % (len(data), data))
        for rec in data.with_progress(msg="Message"):
            print(rec.name)
            sleep(0.1)

        return
```
There's no popup but i notice an icon on the top right showing a green number "1" and then it dissappeared. What is left is just the progress icon.

![image](https://github.com/gmarczynski/odoo-web-progress/assets/7699250/19753acf-1b97-4d55-8cf8-2bd1822c7786)


This code is called in a TransientModel from a pop-up wizard

**Comment by gmarczynski** [comment]
How many records are there in res.partner? Try it with a database having at least 100 records or try this simple iteration:
```python
   def process_file(self):
        for item in self.web_progress_iter(range(100), msg="Message"):
            sleep(.5)
        return
```

It should count up to 100 showing progress by 10 elements every 5 seconds.

**Comment by metalmonkey69** [comment]
It is working now. Thanks !
![image](https://github.com/gmarczynski/odoo-web-progress/assets/7699250/1d5ad3c3-0f86-40c2-baa9-709750f51525)
