### ISSUE TITLE
TypeError: _extract_records() got an unexpected keyword argument 'limit'

### ISSUE THREAD

**Issue by niulinlnc** [gmarczynski/odoo-web-progress#6]
In the latest stable v13 environment, there is no problem with the installation of this module, but when the module is installed, other official modules, such as the hr module, will be reported as follows:
File "xxxxx\odoo\odoo\models.py", line 952, in load Extracted = flush_self._extract_records(fields, data, log=messages.append, limit=limit)
TypeError: _extract_records() got an unexpected keyword argument 'limit'

**Comment by gmarczynski** [comment]
sure, just fixed it

**Comment by niulinlnc** [comment]
Test ok!
